### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by lovehuanhuan** [xuduo35/unet_mxnet2ncnn#1]
When I train ,got these errors:
Traceback (most recent call last):
  File "trainunet.py", line 95, in <module>
    main()
  File "trainunet.py", line 73, in main
    curr_loss = F.mean(loss).asscalar()
  File "/Library/Python/2.7/site-packages/mxnet/ndarray/ndarray.py", line 1990, in asscalar
    return self.asnumpy()[0]
  File "/Library/Python/2.7/site-packages/mxnet/ndarray/ndarray.py", line 1972, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/Library/Python/2.7/site-packages/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [09:22:19] src/operator/nn/./deconvolution-inl.h:224: Check failed: req[deconv::kOut] == kWriteTo (0 vs. 1)

**Comment by xuduo35** [comment]
What value is set for img_width and img_height? I'm using python3.

**Comment by xuduo35** [comment]
Maybe you can refer to this link https://github.com/apache/incubator-mxnet/issues/6644. Try setting 'MXNET_BACKWARD_DO_MIRROR' to '0'.
FYI, I'm using python3 and 'mxnet-cu92 1.3.0.post0' on Ubuntu Linux 16.04.1.

**Comment by hylrh2008** [comment]
maybe you should set this MXNET_BACKWARD_DO_MIRROR to 0
